name: Production

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: login docker
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: setup docker
              uses: docker/setup-buildx-action@v1

            - name: build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/vue-ele:latest
